config/routes.rb
Rails.application.routes.draw do

  root :to => 'static_pages#home'
  get '/help' => 'static_pages#help'

  resources :women do
    collection do
      get :search
    end
  end

end

app/models/woman.rb
class Woman < ActiveRecord::Base

  def self.search query_term
    where("area LIKE ?", "%#{query_term}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/women_controller.rb
class WomenController < ApplicationController
  before_action :set_woman, only: [:show, :edit, :update, :destroy]

  # GET /women
  # GET /women.json
  def index
    @women = Woman.all
  end

  def search
    if params[:query].present?
      @women = Woman.search(params[:query])
    else
      @women = Woman.all
    end
    render :index
  end

  # GET /women/1
  # GET /women/1.json
  def show
  end

  # GET /women/new
  def new
    @woman = Woman.new
  end

  # GET /women/1/edit
  def edit
  end

  # POST /women
  # POST /women.json
  def create
    @woman = Woman.new(woman_params)

    respond_to do |format|
      if @woman.save
        format.html { redirect_to @woman, notice: 'Woman was successfully created.' }
        format.json { render :show, status: :created, location: @woman }
      else
        format.html { render :new }
        format.json { render json: @woman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /women/1
  # PATCH/PUT /women/1.json
  def update
    respond_to do |format|
      if @woman.update(woman_params)
        format.html { redirect_to @woman, notice: 'Woman was successfully updated.' }
        format.json { render :show, status: :ok, location: @woman }
      else
        format.html { render :edit }
        format.json { render json: @woman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /women/1
  # DELETE /women/1.json
  def destroy
    @woman.destroy
    respond_to do |format|
      format.html { redirect_to women_url, notice: 'Woman was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_woman
    @woman = Woman.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def woman_params
    params.require(:woman).permit(:name, :area, :current_position, :linkedin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/women_helper.rb
module WomenHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Convide uma mulher para palestrar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="text-center" style="margin-top: 4px;">
      <a href="/" class="text-center"><%= image_tag("logo.png", size: "51x40" ) %></a>
  </header>
  <div class="body_bg">
    <div class="container fill">
      <div class="row" style="margin-top: 50px;">
        <h1 class="convide text-center col-md-offset-2 col-md-8 col-md-offset-2">Convide uma mulher para palestrar</h1>
        <h2 class="description text-center col-md-offset-2 col-md-8 col-md-offset-2">Acreditamos que uma maior representatividade feminina é possível em eventos, palestras, workshops, entrevistas e projetos por aí :)</h2>
      </div>
      <br/>
      <br/>
      <br/>
      <br/>
      <br/>
      <div class="row">
        <div class="text-center">
          <a class="btn button" href="/women"><button class"btn button" style="font-size: 19px;">Ver lista de mulheres</button></a>
          <a class="btn button" href="/women/new"><button class"btn button" style="font-size: 19px;">Indicar uma mulher incrível</button></a>
        </div>
      </div>
    </div>
  </div>

  <div class="content-container">
    <%= yield %>
  </div>

<footer class="container">
  <div class="row">
    <div class="text-center">
      <a href="http://facebook.com/convideumamulher"><%= image_tag("facebook.png")%></a>
      <a href="https://github.com/guipdutra/convideumamulher"><%= image_tag("github.png")%></a>
    </div>
  </div>
</footer>

</body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/women/_form.html.erb
<%= form_for(@woman) do |f| %>
  <% if @woman.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@woman.errors.count, "error") %> prohibited this woman from being saved:</h2>

      <ul>
      <% @woman.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :area, "Área" %><br>
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :current_position, "Cargo atual" %><br>
    <%= f.text_field :current_position %>
  </div>
  <div class="field">
    <%= f.label :linkedin, "Endereço para LinkedIn" %><br>
    <%= f.text_field :linkedin %>
  </div>
  <div class="actions">
    <%= f.submit "Indicar", class: "btn btn-default" %>
  </div>
<% end %>

app/views/women/edit.html.erb
<h1>Editing woman</h1>

<%= render 'form' %>

<%= link_to 'Show', @woman %> |
<%= link_to 'Back', women_path %>

app/views/women/index.html.erb
<h1>Confira as mulheres já cadastradas</h1>

<%= form_tag(search_women_path, :method => "get") do %>
  <div class="row">
    <div class="col-lg-6">
      <div class="input-group">
        <%= text_field_tag :query, params[:query], placeholder: "Procurar por área", class: "form-control" %>
        <span class="input-group-btn">
          <%= submit_tag "Search", class: "btn btn-default" %>
        </span>
      </div>
    </div>
  </div>
<% end %>

<div class="content">
  <% if @women.present? %>

    <table class="table">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Área</th>
          <th>Cargo atual</th>
          <th>LinkedIn</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @women.each do |woman| %>
          <tr>
            <td><%= woman.name %></td>
            <td><%= woman.area %></td>
            <td><%= woman.current_position %></td>
            <td><%= woman.linkedin %></td>
            <td><%= link_to 'Mais detalhes', woman %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
  <% else %>
    <p> Não encontramos nenhuma mulher na área <strong><%= params[:query] %></strong></p>
  <% end %>

  <%= link_to 'Indicar uma mulher incrível!', new_woman_path %>
</div>

app/views/women/new.html.erb
<h1>Indicar uma mulher incrível!</h1>

<%= render 'form' %>

<%= link_to 'Voltar', women_path %>

app/views/women/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @woman.name %>
</p>

<p>
  <strong>Área:</strong>
  <%= @woman.area %>
</p>

<p>
  <strong>Cargo Atual:</strong>
  <%= @woman.current_position %>
</p>

<p>
  <strong>LinkedIn:</strong>
  <%= @woman.linkedin %>
</p>

<%= link_to 'Editar', edit_woman_path(@woman) %> |
<%= link_to 'Voltar', women_path %>